//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY JSTM                                        
//                                                                              
//==============================================================================

package generatedModel;

import jstm.core.*;

public final class ImagesObjectModel extends jstm.core.ObjectModel {

    public static final String UID = "rBbujaGGGSPRVTCgT8cG3w";

    public static final String XML = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><ObjectModelDefinition xsi:noNamespaceSchemaLocation=\"http://www.xstm.net/schemas/xstm-0.3.xsd\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><Name>ImagesObjectModel</Name><RootPackage name=\"generatedModel\"><Packages/><Structures><Structure name=\"ImageInfo\"><Fields><Field transient=\"false\" name=\"Url\"><Type name=\"java.lang.String\"/></Field><Field transient=\"false\" name=\"Left\"><Type name=\"int\"/></Field><Field transient=\"false\" name=\"Top\"><Type name=\"int\"/></Field><Field transient=\"false\" name=\"zOrder\"><Type name=\"int\"/></Field></Fields><Methods/></Structure></Structures></RootPackage></ObjectModelDefinition>";

    public ImagesObjectModel() {
    }

    @Override
    public String getUID() {
        return UID;
    }

    @Override
    public String getXML() {
        return XML;
    }

    @Override
    public int getClassCount() {
        return 1;
    }

    @Override
    public TransactedObject createInstance(int classId, Connection route) {
        switch (classId) {
            case 0:
                return new generatedModel.ImageInfo();
        }

        throw new IllegalArgumentException("Unknown class id: " + classId);
    }
}
