//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY JSTM                                        
//                                                                              
//==============================================================================

package generatedModel;

import jstm.core.*;

public class ImageInfo extends jstm.core.TransactedStructure {

    public ImageInfo() {
        super(FIELD_COUNT);
    }

    public String getUrl() {
        return (String) getField(0);
    }

    public void setUrl(String value) {
        setField(0, value);
    }

    public int getLeft() {
        java.lang.Integer value = (java.lang.Integer) getField(1);

        if(value != null)
            return value.intValue();

        return 0;
    }

    public void setLeft(int value) {
        setField(1, new java.lang.Integer(value));
    }

    public int getTop() {
        java.lang.Integer value = (java.lang.Integer) getField(2);

        if(value != null)
            return value.intValue();

        return 0;
    }

    public void setTop(int value) {
        setField(2, new java.lang.Integer(value));
    }

    public int getzOrder() {
        java.lang.Integer value = (java.lang.Integer) getField(3);

        if(value != null)
            return value.intValue();

        return 0;
    }

    public void setzOrder(int value) {
        setField(3, new java.lang.Integer(value));
    }

    public static final int URL_INDEX = 0;

    public static final String URL_NAME = "Url";

    public static final int LEFT_INDEX = 1;

    public static final String LEFT_NAME = "Left";

    public static final int TOP_INDEX = 2;

    public static final String TOP_NAME = "Top";

    public static final int ZORDER_INDEX = 3;

    public static final String ZORDER_NAME = "zOrder";

    public static final int FIELD_COUNT = 4;

    @Override
    public String getFieldName(int index) {
        return getFieldNameStatic(index);
    }

    public static String getFieldNameStatic(int index) {
        switch (index) {
            case 0:
                return "Url";
            case 1:
                return "Left";
            case 2:
                return "Top";
            case 3:
                return "zOrder";
            default:
                throw new java.lang.IllegalArgumentException();
        }
    }

    // Internal

    @Override
    protected int getClassId() {
        return 0;
    }

    @Override
    public String getObjectModelUID() {
        return "rBbujaGGGSPRVTCgT8cG3w";
    }

    private static final int[] NON_TRANSIENT_FIELDS = new int[] {  };

    @Override
    protected int[] getNonTransientFields() {
        return NON_TRANSIENT_FIELDS;
    }

    @Override
    protected void serialize(TransactedObject.Version version, Writer writer) throws java.io.IOException {
        boolean[] reads = ((TransactedStructure.Version) version).getReads();
        Object[] values = ((TransactedStructure.Version) version).getWrites();

        if (reads != null) {
            writer.writeShort(Short.MAX_VALUE);

            for (int i = 0; i < 4; i++)
                writer.writeBoolean(reads[i]);
        }

        if (values != null) {
            if (values[0] != null) {
                if (values[0] == Removal.Instance)
                    writer.writeShort((short) -1);
                else {
                    writer.writeShort((short) 1);
                    writer.writeString((String) values[0]);
                }
            }

            if (values[1] != null) {
                if (values[1] == Removal.Instance)
                    writer.writeShort((short) -2);
                else {
                    writer.writeShort((short) 2);
                    writer.writeInteger(((java.lang.Integer) values[1]).intValue());
                }
            }

            if (values[2] != null) {
                if (values[2] == Removal.Instance)
                    writer.writeShort((short) -3);
                else {
                    writer.writeShort((short) 3);
                    writer.writeInteger(((java.lang.Integer) values[2]).intValue());
                }
            }

            if (values[3] != null) {
                if (values[3] == Removal.Instance)
                    writer.writeShort((short) -4);
                else {
                    writer.writeShort((short) 4);
                    writer.writeInteger(((java.lang.Integer) values[3]).intValue());
                }
            }
        }

        writer.writeShort((short) 0);
    }

    @SuppressWarnings("null")
    @Override
    protected void deserialize(TransactedObject.Version version, Reader reader) throws java.io.IOException {
        boolean[] reads = null;
        Object[] values = null;

        short index = reader.readShort();

        if (index == Short.MAX_VALUE) {
            reads = new boolean[4];

            for (int i = 0; i < 4; i++)
                reads[i] = reader.readBoolean();

            index = reader.readShort();
        }

        if (index == 1) {
            if (values == null)
                values = new Object[4];

            values[0] = reader.readString();
            index = reader.readShort();
        } else if (index == -1) {
            if (values == null)
                values = new Object[4];

            values[0] = Removal.Instance;
            index = reader.readShort();
        }

        if (index == 2) {
            if (values == null)
                values = new Object[4];

            values[1] = new java.lang.Integer(reader.readInteger());
            index = reader.readShort();
        } else if (index == -2) {
            if (values == null)
                values = new Object[4];

            values[1] = Removal.Instance;
            index = reader.readShort();
        }

        if (index == 3) {
            if (values == null)
                values = new Object[4];

            values[2] = new java.lang.Integer(reader.readInteger());
            index = reader.readShort();
        } else if (index == -3) {
            if (values == null)
                values = new Object[4];

            values[2] = Removal.Instance;
            index = reader.readShort();
        }

        if (index == 4) {
            if (values == null)
                values = new Object[4];

            values[3] = new java.lang.Integer(reader.readInteger());
            index = reader.readShort();
        } else if (index == -4) {
            if (values == null)
                values = new Object[4];

            values[3] = Removal.Instance;
            index = reader.readShort();
        }

        ((TransactedStructure.Version) version).setReads(reads);
        ((TransactedStructure.Version) version).setWrites(values);
    }
}
