//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY JSTM                                        
//                                                                              
//==============================================================================

package org.epzilla.dispatcher.dispatcherObjectModel;

import jstm.core.*;

public class ClientTriggerStructure extends jstm.core.TransactedStructure {

    public ClientTriggerStructure() {
        super(FIELD_COUNT);
    }

    public String getclientId() {
        return (String) getField(0);
    }

    public void setclientId(String value) {
        setField(0, value);
    }

    public int getvirtualStrata() {
        java.lang.Integer value = (java.lang.Integer) getField(1);

        if(value != null)
            return value.intValue();

        return 0;
    }

    public void setvirtualStrata(int value) {
        setField(1, new java.lang.Integer(value));
    }

    public TransactedList getstructure() {
        return (TransactedList) getField(2);
    }

    public void setstructure(TransactedList value) {
        setField(2, value);
    }

    public static final int CLIENTID_INDEX = 0;

    public static final String CLIENTID_NAME = "clientId";

    public static final int VIRTUALSTRATA_INDEX = 1;

    public static final String VIRTUALSTRATA_NAME = "virtualStrata";

    public static final int STRUCTURE_INDEX = 2;

    public static final String STRUCTURE_NAME = "structure";

    public static final int FIELD_COUNT = 3;

    @Override
    public String getFieldName(int index) {
        return getFieldNameStatic(index);
    }

    public static String getFieldNameStatic(int index) {
        switch (index) {
            case 0:
                return "clientId";
            case 1:
                return "virtualStrata";
            case 2:
                return "structure";
            default:
                throw new java.lang.IllegalArgumentException();
        }
    }

    // Internal

    @Override
    protected int getClassId() {
        return 3;
    }

    @Override
    public String getObjectModelUID() {
        return "cDUa1bEN7HZ5EVpPm+gayQ";
    }

    private static final int[] NON_TRANSIENT_FIELDS = new int[] { 2 };

    @Override
    protected int[] getNonTransientFields() {
        return NON_TRANSIENT_FIELDS;
    }

    @Override
    protected void serialize(TransactedObject.Version version, Writer writer) throws java.io.IOException {
        boolean[] reads = ((TransactedStructure.Version) version).getReads();
        Object[] values = ((TransactedStructure.Version) version).getWrites();

        if (reads != null) {
            writer.writeShort(Short.MAX_VALUE);

            for (int i = 0; i < 3; i++)
                writer.writeBoolean(reads[i]);
        }

        if (values != null) {
            if (values[0] != null) {
                if (values[0] == Removal.Instance)
                    writer.writeShort((short) -1);
                else {
                    writer.writeShort((short) 1);
                    writer.writeString((String) values[0]);
                }
            }

            if (values[1] != null) {
                if (values[1] == Removal.Instance)
                    writer.writeShort((short) -2);
                else {
                    writer.writeShort((short) 2);
                    writer.writeInteger(((java.lang.Integer) values[1]).intValue());
                }
            }

            if (values[2] != null) {
                if (values[2] == Removal.Instance)
                    writer.writeShort((short) -3);
                else {
                    writer.writeShort((short) 3);
                    writer.writeTransactedObject((TransactedObject) values[2]);
                }
            }
        }

        writer.writeShort((short) 0);
    }

    @SuppressWarnings("null")
    @Override
    protected void deserialize(TransactedObject.Version version, Reader reader) throws java.io.IOException {
        boolean[] reads = null;
        Object[] values = null;

        short index = reader.readShort();

        if (index == Short.MAX_VALUE) {
            reads = new boolean[3];

            for (int i = 0; i < 3; i++)
                reads[i] = reader.readBoolean();

            index = reader.readShort();
        }

        if (index == 1) {
            if (values == null)
                values = new Object[3];

            values[0] = reader.readString();
            index = reader.readShort();
        } else if (index == -1) {
            if (values == null)
                values = new Object[3];

            values[0] = Removal.Instance;
            index = reader.readShort();
        }

        if (index == 2) {
            if (values == null)
                values = new Object[3];

            values[1] = new java.lang.Integer(reader.readInteger());
            index = reader.readShort();
        } else if (index == -2) {
            if (values == null)
                values = new Object[3];

            values[1] = Removal.Instance;
            index = reader.readShort();
        }

        if (index == 3) {
            if (values == null)
                values = new Object[3];

            values[2] = reader.readTransactedObject();
            index = reader.readShort();
        } else if (index == -3) {
            if (values == null)
                values = new Object[3];

            values[2] = Removal.Instance;
            index = reader.readShort();
        }

        ((TransactedStructure.Version) version).setReads(reads);
        ((TransactedStructure.Version) version).setWrites(values);
    }
}
